### ISSUE TITLE
Add space around "="

### ISSUE THREAD

**Issue by Airkro** [kddeisz/prettier-plugin-ini#19]
example:

```ini
key = value
```

**Comment by kddeisz** [comment]
INI is pretty ill-defined, but in some implementations it considers everything after the `=` part of the value, so I'm going to leave it as it is for now.

**Comment by Airkro** [comment]
Point taken, but for some ini-like format, it still can be supported. (.npmrc, .editorconfig, etc.)

How about adding an option (default: false). The user who knows the risk can use it.

**Comment by kddeisz** [comment]
@Airkro yeah that makes total sense. Just released v0.3.0 with the `iniSpaceAroundEquals` option.
